# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Driver.create(name: "Alexis Perez")
Driver.create(name: "Anthony Toller")
Driver.create(name: "Kareem Andrews")
Driver.create(name: "Dylan Cuffee")
Driver.create(name: "Anthony Montgomery")
Driver.create(name: "Jerel Hopkins")
Driver.create(name: "Reginald Stallworth")
Driver.create(name: "Waldemar Perez")
Driver.create(name: "Edward Vega")
Driver.create(name: "Adriano Medeiros")
Driver.create(name: "Dennis Jackson")
Driver.create(name: "Daniel Quiles")
Driver.create(name: "Victor Perez")
Driver.create(name: "Sedric Brooks")
Driver.create(name: "Raynel Forbes")
Driver.create(name: "William Dean")
Driver.create(name: "Daryl Doniel")
Driver.create(name: "Carlos Tome")
Driver.create(name: "Marcus Smalls")
Driver.create(name: "Marco Ortiz")
Driver.create(name: "Gregory King")
Driver.create(name: "Sammuel Bailey")
Driver.create(name: "Andrew Leonard Sharp")
Driver.create(name: "Taurus Epting")
Driver.create(name: "Jason Graves")
Driver.create(name: "Nicholas Ryan Simon")
Driver.create(name: "Jamal Theodis Walker")
Driver.create(name: "Eduardo Ganga")
Driver.create(name: "Deangelo Mccoy")
Driver.create(name: "Joares Maura")
Driver.create(name: "Donald Gregory")
Driver.create(name: "Bryan Rose")
Driver.create(name: "Victor")
Driver.create(name: "Chris Cummins")
Driver.create(name: "Thais Malon")
